### PR TITLE
Fix nova 4 support

### PR DESCRIPTION
**Pull request by mark-b-ab**

### CODE REVIEW

**Comment by bernhardh** [comment]
Thanks for your PR! I don't have nova 4, so I can't test ist atm. But why this PR? I merged another a couple of months ago just to add these lines of code. See https://github.com/bernhardh/nova-dynamic-views/pull/12

**Comment by Marko298** [comment]
You haven't imported Request from \Request

**Comment by Marko298** [comment]
It crashes if you try to install

**Comment by bernhardh** [comment]
So the solution would be, to import it, right? Can you test it and change your PR? As I said, I have no nova 4, so I cant test it.

**Comment by Marko298** [comment]
Can give me your email?

**Comment by bernhardh** [comment]
I am normally reluctant to share my private e-mail adress on the web. You can provide any infos in this ticket.

**Comment by Marko298** [comment]
Write me anything here mark.boichuk@nuant.com. I will send you Nova 4

**Comment by bernhardh** [comment]
In `master` branch, there was already the correct namespace. I don't know why, it wasn't in `1.5.0`. Now in `1.5.1` I have added it. 

But I don't think it works, even after this fix. There is no error, but the toolbar isn't shown. I have no clue and at the moment no time to fix this. Maybe something changed internally in nova4. To be honest, the toolbar logic of nova is very bad (or was at least for version 3), thats why I created this package in the first place. Since I switched to the way better filamentphp as an admin panel, I don't use nova anymore.

If you find a solution, you can create an PR.

**Comment by Marko298** [comment]
Got it, thanks for your time!

**Pull request closed without merging**
